schema_version: 1

context:
  name: fast-simplification
  version: 0.2.0
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|replace("-", "_")|lower }}-${{ version }}.tar.gz
  sha256: ed02ea6f4968ec98f963f2d3665dbafd0297ec12aea9e4d0a87c4b3c14d608a8

build:
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    # Build system.
    - nanobind >=1.3.2
    - setuptools-scm >=8
    - scikit-build-core >=0.10
    # Dependencies.
    - pip
    - python ${{ python_min }}.*
  run:
    - numpy
tests:
  - python:
      imports:
        - fast_simplification
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - pytest ./tests/
    files:
      source:
        - tests/
    requirements:
      run:
        - pyvista
        - pytest

about:
  homepage: https://pyvista.github.io/fast-simplification
  license: MIT
  license_file: LICENSE
  repository: https://github.com/pyvista/fast-simplification
  summary: Fast Quadratic Mesh Simplification

extra:
  recipe-maintainers:
    - diegoferigo
    - akaszynski
